spring:
  application:
  name: cso

  datasource:
    sql-cso:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mysql.mhha.kr:33066/cso
      username: cso
      password: Tldptmdh1234

    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 6000
      max-lifetime: 18000
      keepalive-time: 600
      leak-detection-threshold: 200
      connection-test-query: "SELECT 1"

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jackson:
    time-zone: Asia/Seoul

  jwt:
    secret: 65748520123456788765432165748520

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    async:
      request-timeout: -1

  http-port: 25801


server:
  port: 25800
  ssl:
    key-store: dev-back-cso.mhha.kr.jks
    key-store-password: 'dev_back_cso_mhha_ssl'
  shutdown: immediate
  forward-headers-strategy: native

logging:
  level:
    web: debug
    org:
      springframework:
        web: debug
      hibernate:
        sql: debug
        type: debug

file:
  defDir: C:/FTP/STORAGE
  imageDir: C:/FTP/STORAGE/IMAGE
  documentDir: C:/FTP/STORAGE/DOCUMENT
  userExcelDir: C:/FTP/STORAGE/EXCEL/USER
  pharmaExcelDir: C:/FTP/STORAGE/EXCEL/PHARMA
  hospitalExcelDir: C:/FTP/STORAGE/EXCEL/HOSPITAL
  medicineExcelDir: C:/FTP/STORAGE/EXCEL/MEDICINE
  medicineIngredientExcelDir: C:/FTP/STORAGE/EXCEL/MEDICINE_INGREDIENT
  medicinePriceExcelDir: C:/FTP/STORAGE/EXCEL/MEDICINE_PRICE
  ediDueDateExcelDir: C:/FTP/STORAGE/EXCEL/EDI_DUE_DATE
  userMappingExcelDir: C:/FTP/STORAGE/EXCEL/USER_MAPPING
  hospitalTempExcelDir: C:/FTP/STORAGE/EXCEL/HOSPITAL_TEMP
  pharmacyTempExcelDir: C:/FTP/STORAGE/EXCEL/PHARMACY_TEMP
  #linux path
#  defDir: /home/FTP/STORAGE
#  imageDir: /home/FTP/STORAGE/IMAGE
#  documentDir: /home/FTP/STORAGE/DOCUMENT
#  userExcelDir: /home/FTP/STORAGE/EXCEL/USER
#  pharmaExcelDir: /home/FTP/STORAGE/EXCEL/PHARMA
#  hospitalExcelDir: /home/FTP/STORAGE/EXCEL/HOSPITAL
#  medicineExcelDir: /home/FTP/STORAGE/EXCEL/MEDICINE
#  medicineIngredientExcelDir: /home/FTP/STORAGE/EXCEL/MEDICINE_INGREDIENT
#  medicinePriceExcelDir: /home/FTP/STORAGE/EXCEL/MEDICINE_PRICE
#  ediDueDateExcelDir: /home/FTP/STORAGE/EXCEL/EDI_DUE_DATE
#  userMappingExcelDir: /home/FTP/STORAGE/EXCEL/USER_MAPPING
#  hospitalTempExcelDir: /home/FTP/STORAGE/EXCEL/HOSPITAL_TEMP
#  pharmacyTempExcelDir: /home/FTP/STORAGE/EXCEL/PHARMACY_TEMP

str:
  version: 1.0.0
  profile: dev
  blob:
    blobUrl: https://mhhablob1.blob.core.windows.net
    containerName: mhhablob1
    defaultKey: y85lApcIsXQ5znb9/G2axqe8V/dwKfcg0dn8WTtd35vPrFbj/XNv7qOi6aOVBi0Qx8DxLh4ZZMF3+ASt/K9zPA==
    subKey: /9enjdo1lvLbN48QO47gZiF5w8CzKuaV7rBZfA8vlbLxfEppmjgAKtMjPxYnH4eDVr0ejBQvRq88+AStz4LMdA==
    connectionString: DefaultEndpointsProtocol=https;AccountName=mhhablob1;AccountKey=y85lApcIsXQ5znb9/G2axqe8V/dwKfcg0dn8WTtd35vPrFbj/XNv7qOi6aOVBi0Qx8DxLh4ZZMF3+ASt/K9zPA==;EndpointSuffix=core.windows.net

mqtt:
  brokerUrl1: tcp://mqtt.mhha.kr:18883
  brokerUrl2: wss://mqtt.mhha.co.kr:18884
  clientId: def-cso-mqtt
  username: mqtt
  password: mqtt1234