spring:
  application:
  name: cso

  datasource:
    sql-cso:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://10.0.0.7:33066/cso
      username: cso
      password: Tldptmdh1234

    hikari:
      max-lifetime: 3500000

  messages:
    basename: i18n/exception
    encoding: UTF-8

  jackson:
    time-zone: Asia/Seoul

  jwt:
    secret: 65748520123456788765432165748520

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    async:
      request-timeout: -1

  http-port: 25801


server:
  port: 25800
  ssl:
    key-store: back-cso.sdmed.co.kr.jks
    key-store-password: 'back_cso_sdmed_ssl'
  shutdown: immediate
  forward-headers-strategy: native

logging:
  level:
    web: debug
    org:
      springframework:
        web: debug
      hibernate:
        sql: debug
        type: debug

file:
  defDir: C:/FTP/STORAGE
  imageDir: C:/FTP/STORAGE/IMAGE
  documentDir: C:/FTP/STORAGE/DOCUMENT
  userExcelDir: C:/FTP/STORAGE/EXCEL/USER
  pharmaExcelDir: C:/FTP/STORAGE/EXCEL/PHARMA
  hospitalExcelDir: C:/FTP/STORAGE/EXCEL/HOSPITAL
  medicineExcelDir: C:/FTP/STORAGE/EXCEL/MEDICINE
  medicineIngredientExcelDir: C:/FTP/STORAGE/EXCEL/MEDICINE_INGREDIENT
  medicinePriceExcelDir: C:/FTP/STORAGE/EXCEL/MEDICINE_PRICE
  ediDueDateExcelDir: C:/FTP/STORAGE/EXCEL/EDI_DUE_DATE
  userMappingExcelDir: C:/FTP/STORAGE/EXCEL/USER_MAPPING

str:
  version: 1.0.0
  profile: prod
  blob:
    blobUrl: https://devsdmed1.blob.core.windows.net
    containerName: devsdmed1
    defaultKey: s31JKySWQQ67+LQ/o79G0yOdc9QE1408KuANaZdiVupmU3Q6DRGmUpsMmR1UNK/2WcuIMCrp5rdt+ASt4LY89Q==
    subKey: /9enjdo1lvLbN48QO47gZiF5w8CzKuaV7rBZfA8vlbLxfEppmjgAKtMjPxYnH4eDVr0ejBQvRq88+AStz4LMdA==
    connectionString: DefaultEndpointsProtocol=https;AccountName=devsdmed1;AccountKey=s31JKySWQQ67+LQ/o79G0yOdc9QE1408KuANaZdiVupmU3Q6DRGmUpsMmR1UNK/2WcuIMCrp5rdt+ASt4LY89Q==;EndpointSuffix=core.windows.net

mqtt:
  brokerUrl1: tcp://mqtt-cso.sdmed.co.kr:18883
  brokerUrl2: wss://mqtt-cso.sdmed.co.kr:18884
  clientId: def-cso-mqtt
  username: cso
  password: csoMQ1234