spring:
  application:
  name: cso

  datasource:
    sql-cso:
#      driver-class-name: com.mysql.jdbc.Driver
#      jdbc-url: jdbc:mysql://db.mhha.kr:33066/cso
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://db.mhha.kr:14333;encrypt=true;trustServerCertificate=true
#      jdbc-url: jdbc:sqlserver://127.0.0.1:1433;encrypt=true;trustServerCertificate=true
      username: cso
      password: 1234


  messages:
    basename: i18n/exception
    encoding: UTF-8

  jackson:
    time-zone: Asia/Seoul

  jwt:
    secret: 65748520123456788765432165748520

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    async:
      request-timeout: -1

  http-port: 25801


server:
  port: 25800
  ssl:
    key-store: back.cso.mhha.kr.jks
    key-store-password: 'back_cso_mhha_ssl'
  shutdown: immediate
  forward-headers-strategy: native

logging:
  level:
    web: debug
    org:
      springframework:
        web: debug
      hibernate:
        sql: debug
        type: debug

file:
  defDir: C:/FTP/STORAGE
  imageDir: C:/FTP/STORAGE/IMAGE
  documentDir: C:/FTP/STORAGE/DOCUMENT
  userExcelDir: C:/FTP/STORAGE/EXCEL/USER
  pharmaExcelDir: C:/FTP/STORAGE/EXCEL/PHARMA
  hospitalExcelDir: C:/FTP/STORAGE/EXCEL/HOSPITAL
  medicineExcelDir: C:/FTP/STORAGE/EXCEL/MEDICINE
  medicineIngredientExcelDir: C:/FTP/STORAGE/EXCEL/MEDICINE_INGREDIENT
  medicinePriceExcelDir: C:/FTP/STORAGE/EXCEL/MEDICINE_PRICE

str:
  version: 1.0.0
  profile: dev
  blob:
    containerName: mhhablob1
    defaultKey: y85lApcIsXQ5znb9/G2axqe8V/dwKfcg0dn8WTtd35vPrFbj/XNv7qOi6aOVBi0Qx8DxLh4ZZMF3+ASt/K9zPA==
    subKey: 04pB8z/clKXfA8ezNU/waivZJzyEaEGNtok5WapPABEFnAFJwyy1mwv/s3QypzO2ojZXwrqAmoRI+AStGeD1BA==
    connectionString: DefaultEndpointsProtocol=https;AccountName=mhhablob1;AccountKey=y85lApcIsXQ5znb9/G2axqe8V/dwKfcg0dn8WTtd35vPrFbj/XNv7qOi6aOVBi0Qx8DxLh4ZZMF3+ASt/K9zPA==;EndpointSuffix=core.windows.net

mqtt:
  brokerUrl1: tcp://mqtt-cos.sdmed.co.kr:18883
  brokerUrl2: wss://mqtt-cso.sdemd.co.kr:18884
  clientId: def-cso-mqtt
  username: cso
  password: csoMQ1234